version: '3.3'

networks:
  mongo_net:
    driver: bridge

volumes:
  mongo_volume:

services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb 
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo3 
      MONGO_INITDB_ROOT_PASSWORD: mongo3
    ports:
      - 27017:27017
    networks:
      - mongo_net 
    volumes:
      - mongo_volume:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root 
      ME_CONFIG_BASICAUTH_PASSWORD: root123
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo3 
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo3
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo_net 
    ports:
      - 8081:8081